name: fruit_dashboard
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^6.0.1
  dartz: ^0.10.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: 1.9.0
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_launcher_icons: '^0.14.4'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  uses-material-design: true
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/Fruits_Logo.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
