name: fruit_dashboard
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dartz: ^0.10.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: 1.9.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_launcher_icons: '^0.14.4'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/Fruits_Logo.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
