// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6xtgfvGWSqVqNpS4JOOrGHionntb5-hU',
    appId: '1:423190213812:web:dac6fe6ebefa1b317853e1',
    messagingSenderId: '423190213812',
    projectId: 'ecomerce-fruit-hub',
    authDomain: 'ecomerce-fruit-hub.firebaseapp.com',
    storageBucket: 'ecomerce-fruit-hub.firebasestorage.app',
    measurementId: 'G-0DCCZWBYSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1IGswm2uPO1OFPJxid8_P6XvN7tYF59Y',
    appId: '1:423190213812:android:7b4a96b8dc10b3ff7853e1',
    messagingSenderId: '423190213812',
    projectId: 'ecomerce-fruit-hub',
    storageBucket: 'ecomerce-fruit-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFaBtv4Cjscw7I_AVaRepKmOulYp_g-7A',
    appId: '1:423190213812:ios:370571ed571732647853e1',
    messagingSenderId: '423190213812',
    projectId: 'ecomerce-fruit-hub',
    storageBucket: 'ecomerce-fruit-hub.firebasestorage.app',
    androidClientId: '423190213812-bg924puisd38c7v9jpvj6hl3ikjb71th.apps.googleusercontent.com',
    iosClientId: '423190213812-64ond9hh6fvfjak7ugpq35n4qkoorta2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitDashboard',
  );
}
